version: "3.7"
services:
  app:
    stdin_open: true
    tty: true
    build:
      context: .
    command: bash ../app/run_dockerized_app.sh
    volumes:
      - .:/app:delegated
    ports:
      - "4000:4000"